### ISSUE TITLE
add systemd-executor

### ISSUE THREAD

**Issue by lnussel** [openSUSE/dracut#295]
Not sure what comes first, a new dracut release or systemd. If the latter we'll need https://github.com/dracutdevs/dracut/commit/bee1c4824a8cd47ce6c01892a548bdc07b1fa678 in Factory. So just a heads up as systemd is preparing for a new release.

**Comment by aafeijoo-suse** [comment]
> Not sure what comes first, a new dracut release or systemd.

A systemd release for sure.

> If the latter we'll need [dracutdevs@bee1c48](https://github.com/dracutdevs/dracut/commit/bee1c4824a8cd47ce6c01892a548bdc07b1fa678) in Factory. So just a heads up as systemd is preparing for a new release.

Thanks for the heads-up! We are aware that we need some stuff for systemd-v255, also:
- https://github.com/dracutdevs/dracut/pull/2526
- https://github.com/dracutdevs/dracut/pull/2527
- https://github.com/dracutdevs/dracut/pull/2528

**Comment by keszybz** [comment]
I backported the patches listed here for Fedora rawhide, and it seems to do the trick. Very useful list ;)

**Comment by aafeijoo-suse** [comment]
> I backported the patches listed here for Fedora rawhide, and it seems to do the trick. Very useful list ;)

Thanks for your feedback, happy to help!

**Comment by fbuihuu** [comment]
> > Not sure what comes first, a new dracut release or systemd.
> 
> A systemd release for sure.

Hm not sure to understand why since `systemd-executor` is going to be released very soon anyway and IIUC without dracutdevs@bee1c48 any system based on v255 won't boot.

Why can't dracutdevs@bee1c48  (at least) be backported already so the integration and the submit of v255 will be easier for us ?
